language: php
php:
  - 5.3
  - 5.4
services:
  - mysql
before_script:
  - mysql -e 'create database testdb;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer self-update
  - composer install --no-progress --dev
script: "cd tests/ && ../libs/bin/phpunit Flame/"